### ISSUE TITLE
efi folder

### ISSUE THREAD

**Issue by robi62** [Yoshi2889/840g2-opencore-config#1]
hi your efi folder is incomplete Cannot boot from it has it has stuff missing like kexts etc etc
Can you upload a working efi???
Thanks

**Comment by NanoSector** [comment]
Hi, thanks for opening an issue, this is by design as this repo is used for documenting the setup I use for this particular machine. Hackintoshing works better if you have an idea of what you are doing.
That, and redistributing complete EFI folders is frowned upon because of serial numbers and Apple binaries in those, etc.

I'd recommend following the [OpenCore guide](https://dortania.github.io/OpenCore-Install-Guide/) and applying the settings from this repo where needed.

All the used kexts are listed in the README, you can download them from the respective linked repositories. Let me know if you run into any trouble with this specifically.

**Comment by robi62** [comment]
Hi thanks for reply I alway/  change serial numbers when I use efi folders. I recreate your efi which I believe was oc 74 but machine wont boot nothing happens, no screen nothing just a blank screen .
Not sure how I can make it boot.Maybe something is wrong with config file??
Regards
