### ISSUE TITLE
840G2 with Opencore 0.7.9 and Monterey: very slow to boot and after sleep, without keyboard

### ISSUE THREAD

**Issue by voducngh** [Yoshi2889/840g2-opencore-config#2]
very slow to boot.
from the boot screen, the indicateur makes a offshift status bar

when on idle, the system goes to sleep. but unable to wake up with keyboard unresponsive.

I had to update the OpenIntelwifi for Monterey.

May be I should don't upgrade to Monterey !!

**Comment by NanoSector** [comment]
Hi, sorry for not replying sooner.

> very slow to boot. from the boot screen, the indicateur makes a offshift status bar

I recognise the slow booting issue, this might be due to the high APFS TRIM timeout or other factors. macOS boots fairly slow on real Macs as well.

I am not sure what you mean with "offshift status bar".

> when on idle, the system goes to sleep. but unable to wake up with keyboard unresponsive.

This is also an issue on Windows and Linux in my experience.

> I had to update the OpenIntelwifi for Monterey.
> 
> May be I should don't upgrade to Monterey !!

Sorry, I don't use Intel wifi in this machine. I recommend buying a Broadcom card for macOS.
